### ISSUE TITLE
Problem in Heuristically Cacheable Logic?

### ISSUE THREAD

**Issue by parkerhancock** [karpetrosyan/hishel#108]
As I was looking through the code, I think I noticed an issue with how `allow_heuristics` is implemented. In `_controller.py`, the `is_cacheable` logic processes the `_cacheable_status_codes` before it processes the `HEURISTICALLY_CACHEABLE` status codes:

```python
class Controller:
   def __init__(
   ...
   ):
        self._cacheable_status_codes = (
            cacheable_status_codes if cacheable_status_codes else [200, 301, 308]
        )
   ...
   def is_cachable(self, request: Request, response: Response) -> bool:
      ...
      if response.status not in self._cacheable_status_codes:
            return False
      ...
      if self._allow_heuristics and response.status in HEURISTICALLY_CACHABLE:
            return True
```
What this means is that if you set `allow_heuristics` to `True`, but don't pass in `cacheable_status_codes`, the cache will never cache the full list of `HEURISTICALLY_CACHEABLE` status codes. 

Is this expected behavior? Or if `allow_heuristics` is set to `True`, but `cacheable_status_codes` is not passed, should `cacheable_status_codes` default to the full list of `HEURISTICALLY_CACHEABLE` status codes, rather than just `[200, 301, 308]`?

I might suggest that the `__init__` method be modified like this:

```python
class Controller:
   def __init__(
   ...
   ):
        if cacheable_status_codes:
           self._cacheable_status_codes = cacheable_status_codes
        elif allow_heuristics:
           self._cacheable_status_codes = HEURISTICALLY_CACHEABLE
        else:
           self._cacheable_status_codes = [200, 301, 308]
```

Thoughts?

**Comment by karpetrosyan** [comment]
Thanks for this issue @parkerhancock!
Actually, this is expected behavior, even if it is incorrect :smile: .

I have tried to avoid obvious things and enforce the status code list that the user provides.
When the user enables the heuristic caching, he should also enable the status codes that he wants to cache from that list.

I think we should stick with the idea that explicit is better than implicit and not change anything there, maybe excluding documentation where we can outline that.

**Comment by parkerhancock** [comment]
Interesting! Thanks for the response. The tip in the [controller documentation](https://hishel.com/advanced/controllers/) points to the RFC 9111 specification, which in turn does discuss that only some status codes are heuristically cacheable, but then you have to go through each enumerated status code in the spec to see if it is heuristically cacheable. I might submit a simple PR to expand those docs to just say that RFC 9111 only allows heuristic caching of certain status codes, and provide a list. That would have clarified it for me!

**Comment by karpetrosyan** [comment]
> I might submit a simple PR to expand those docs to just say that RFC 9111 only allows heuristic caching of certain status codes, and provide a list. That would have clarified it for me!

It would be fantastic! 
Also, we should note in the documentation that if you enable heuristic caching but do not change the allowed status codes, heuristic caching will not work ( we can do it using 'warning!' ).

Thank you for your efforts :pray:. 
I have sent you a [collaborator](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/permission-levels-for-a-personal-account-repository#collaborator-access-for-a-repository-owned-by-a-personal-account) invite, which you can accept for more control over `Hishel`.
