### ISSUE TITLE
Shouldn't be less than sign?!

### ISSUE THREAD

**Issue by HassanRady** [karpetrosyan/hishel#118]
https://github.com/karpetrosyan/hishel/blob/34231cc421a74fbe1d40f11a7e548347576de12a/hishel/_async/_storages.py#L236C86-L236C86

**Comment by karpetrosyan** [comment]
`DELETE FROM cache WHERE datetime(date_created, '+{self._ttl} seconds') > datetime()`

it's correct

x = creation time
y = current time

remove if x + ttl > y

**Comment by HassanRady** [comment]
async with self._lock:
            await self._connection.execute("DELETE FROM cache WHERE key = ?", [key])
            serialized_response = self._serializer.dumps(response=response, request=request, metadata=metadata)
            await self._connection.execute("INSERT INTO cache(key, data) VALUES(?, ?)", [key, serialized_response])
            await self._connection.commit()
        await self._remove_expired_caches()  (here)

x = 2023-11-29 12:26:08
ttl = 86400
x + ttl = 2023-11-30 12:26:08
y = 2023-11-29 12:26:08

it will be removed!

sorry, if i am missing something?

**Comment by karpetrosyan** [comment]
OOps, it seems I have missed something!
I am wondering how it passes the test cases that we have.

Goot catch, thank you :pray:
Do you want to submit a PR that resolves this?

**Comment by HassanRady** [comment]
Yes, I will submit a PR.

**Comment by karpetrosyan** [comment]
Resolved in #119
