### ISSUE TITLE
Implement compression

### ISSUE THREAD

**Issue by Simon-Will** [karpetrosyan/hishel#132]
It would be nice if the cache entries could be compressed in order to save disk space. If you agree that this would be a useful and valid feature, I could try an implementation.

Maybe it would be an option to be passed to serializers? Or part of the storage? What do you think?

**Comment by parkerhancock** [comment]
Hey! You can do this pretty easily with the existing codebase. Storages take serializers as initialization arguments, and serializers just need to implement a `loads` and `dumps` method. So just subclass one of the serializers (pickle/json/yaml), and wrap the `dumps/loads` methods with the compression library of your choice.

```python
import gzip
import hishel

class CompressedJsonSerializer(hishel.JSONSerializer):
  def dumps(self, *args, **kwargs):
    data = super().dumps(*args, **kwargs)
    return gzip.compress(data.encode())
  
  def loads(self, data):
    uncompressed = gzip.decompress(data).decode()
    return super().loads(uncompressed)

  @property
  def is_binary(self): # flag for storages to let them know the return type is now bytes and not str
    return True

client = hishel.CacheClient(
  storage=hishel.FileStorage(serializer=CompressedJsonSerializer)
  )
```

**Comment by karpetrosyan** [comment]
Excellent solution, Parker! 
I believe we should have a section in the documentation for scenarios like this.

We could write solutions to a variety of common problems so that the user reading that section understands how adaptable this library is and how they can write their own custom things.
