### ISSUE TITLE
AttributeError: 'OpsController' object has no attribute '_key_generator'

### ISSUE THREAD

**Issue by echoopen** [karpetrosyan/hishel#144]
I have this problem, what's the reason?

AttributeError: 'OpsController' object has no attribute '_key_generator'

**Comment by parkerhancock** [comment]
_key_generator was added in v0.0.20. You must be running an earlier version of Hishel with software that requires v0.0.20.

```
pip install --upgrade hishel
```

**Comment by echoopen** [comment]
I do have the latest version but still have this error

**Comment by karpetrosyan** [comment]
Hi! Can you provide more information about the problem, such as installed packages, Python version, Hishel version, and code that reproduces the problem?

**Comment by echoopen** [comment]
![image](https://github.com/karpetrosyan/hishel/assets/62507651/e81df90d-488c-474b-bf8c-e5ce0c55c2a1)

python3.10

import os

# 设置环境变量
os.environ['PATENT_CLIENT_EPO_API_KEY'] = "k"
os.environ['PATENT_CLIENT_EPO_SECRET'] = "yD"

from patent_client import Inpadoc
case = Inpadoc.objects.get("EP1000000A1")

**Comment by parkerhancock** [comment]
Not a hishel problem. Closing
