### ISSUE TITLE
Transport socket unclosed

### ISSUE THREAD

**Issue by yanyongyu** [karpetrosyan/hishel#145]
The http transport is not closed even if the http client is already closed.

```
ResourceWarning: unclosed <ssl.SSLSocket ...>
```

related to:
https://github.com/yanyongyu/githubkit/pull/62

Reproduce code:

```python
import gc
import warnings

from hishel import CacheClient

warnings.simplefilter("default")

def main():
    with CacheClient() as client:
        client.get("https://httpbin.org/get")

    del client

    gc.collect()

main()
```

**Comment by karpetrosyan** [comment]
Thank you for bringing this up. 
Closing the inner transport in the lines you mentioned in https://github.com/yanyongyu/githubkit/pull/62 will resolve this issue. Would you like to open a pull request to resolve this issue?

**Comment by yanyongyu** [comment]
Should we provide an option to automatically close the inner transport provided by user? As user may not want the transport closed in some special case.

**Comment by karpetrosyan** [comment]
Are there any good examples when users would wish to keep the real transport open?

**Comment by yanyongyu** [comment]
I'm not sure if there are good examples, may be transport reusing?

**Comment by karpetrosyan** [comment]
Closing transport in HTTPX does not break the transport, and you can still use it. It just closes all the socket connections on that transport.

For example:

```python
import httpx

request = httpx.Request('GET', 'https://www.google.com')

transport = httpx.HTTPTransport()

with transport:
    response = transport.handle_request(request)
    print(response.status_code)

with transport:
    response = transport.handle_request(request)
    print(response.status_code)
```

**Comment by yanyongyu** [comment]
That's good. I will create a pr to add transport/pool close to cachetransport/cachepool.
