### ISSUE TITLE
[Feature Request] Installation with conda package manager

### ISSUE THREAD

**Issue by umnovI** [karpetrosyan/hishel#150]
Hi,
I'm using  conda as my environment and package manager. And it is [not recommended](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages) to install packages with pip. Plus it is harder to maintain the environment when using conda and pip.

I was wondering if there are any plans on releasing hishel on one of the conda's channels like conda-forge?

**Comment by parkerhancock** [comment]
Love this idea!

I just submitted the recipe here: (https://github.com/conda-forge/staged-recipes/pull/24887). I'll see if I can get it through. I'm trying to do the same for a downstream of `hishel` so I'll keep an eye on it.

@karpetrosyan, can you please comment on the conda-forge PR just to confirm that you are a maintainer?

Thanks!

Parker

**Comment by umnovI** [comment]
Hishel has been merged into conda-forge channel 🎉🎉🎉 https://github.com/conda-forge/staged-recipes/pull/24887#event-12313327807
Closing as completed.
