### ISSUE TITLE
Performance drops as the number of cache files increases.

### ISSUE THREAD

**Issue by umnovI** [karpetrosyan/hishel#167]
Hi,
I've noticed a significant performance drop with `AsyncFileStorage` with large amount of files in cache. 

Current cache count is 1494 files.

![image](https://github.com/karpetrosyan/hishel/assets/30232564/cad89ea1-a467-4faa-9224-d59570d3e109)
![total_requests_per_second_1705917148](https://github.com/karpetrosyan/hishel/assets/30232564/51639156-4ee7-456b-87f2-6739c1b9965c)

Compared to clean cache directory.

![image](https://github.com/karpetrosyan/hishel/assets/30232564/0742a157-5291-4119-a45d-674464ad8668)
![total_requests_per_second_1705917293](https://github.com/karpetrosyan/hishel/assets/30232564/33259230-2fcc-4e98-ab35-776776c24811)

Settings:
```python
CACHE_TTL = {"11days": 950400}
HISHEL_STORAGE = hishel.AsyncFileStorage(ttl=CACHE_TTL["11days"])
HISHEL_CONTROLLER = hishel.Controller(allow_stale=True)
HISHEL_CLIENT = hishel.AsyncCacheClient(
    storage=HISHEL_STORAGE,
    controller=HISHEL_CONTROLLER,
    limits=Limits(max_connections=50),
)
```
For example, measurements for:
```python
        print("Requesting..", request_url, req.query)

        start = time.time()
        response = await client.get(request_url, timeout=3, params=req.query)
        end = time.time()
        print("Elapsed time during client.get: ", end - start)
        print(response.elapsed)
```

```
Requesting.. https://pokeapi.co/api/v2/pokemon/ {}
Elapsed time during client.get:  0.9087388515472412
0:00:00.906000
From cache: True
```

Is there a way to avoid such serious performance drop?

**Comment by umnovI** [comment]
Setting cache ttl causes hishel to iterate through **every** file to check if it's stale during **every** call. 
Deleting `ttl=CACHE_TTL["11days"]` reduces response time to 20+ ms.
So, I guess, issue is closed?

**Comment by karpetrosyan** [comment]
Hi! 
I was trying to find a time to dive deeper into this issue, but you did it yourself! Thank you

If there is no performance issue, we can close this.
If you discover any other performance problems, I will appreciate issues like this.

**Comment by umnovI** [comment]
Sure. You can close it.
But just an idea. Maybe `_remove_expired_caches` should check staleness of only the current file? If cache has 2000 or more files it would be awful to check staleness for every file for every request.

**Comment by karpetrosyan** [comment]
> Maybe _remove_expired_caches should check staleness of only the current file?

Yeah, its' a good idea, thanks.
In that case we need some logic that will periodically remove stale files.

Would you like to issue a pull request for that?

**Comment by karpetrosyan** [comment]
I believe that we shouldn't really focus on manual removal because users frequently forget or simply aren't aware of it.

Instead, we can choose to clear the cache every X seconds; I believe that 60 seconds will work well by default.
I believe that `AsyncS3Storage` has the similar issue, therefore we should definitely implement this for that storage as well.

**Comment by umnovI** [comment]
@karpetrosyan, is there any way to test `AsyncS3Storage`? I see it has `# pragma: no cover` too.

**Comment by karpetrosyan** [comment]
There is no integration test for S3(

**Comment by umnovI** [comment]
Could this be useful? https://pypi.org/project/moto/
Looks like it can mock AWS

**Comment by umnovI** [comment]
> Instead, we can choose to clear the cache every X seconds; I believe that 60 seconds will work well by default.

Should it be an exposed parameter, so a user could set it too? Something like `clear_cache_every: int = 60`

**Comment by karpetrosyan** [comment]
> Should it be an exposed parameter, so a user could set it too? Something like `clear_cache_every: int = 60`

It's up to you. I think it would be neater.

**Comment by karpetrosyan** [comment]
> Could this be useful? https://pypi.org/project/moto/

I think yes. I have tried [localstack](https://www.localstack.cloud/) that doesn't work for me.

**Comment by umnovI** [comment]
I can create pull request for `filesorage`. I'm thinking maybe `AsyncS3Storage` should be a different pull request.

**Comment by karpetrosyan** [comment]
> I can create a pull request for `filestorage`. I'm thinking maybe `AsyncS3Storage` should be a different pull request.

Yep. I think fixing them in different PRs is more correct

**Comment by umnovI** [comment]
> And also, we could have a different PR that adds tests for S3 using moto

Yes, I think tests should be first though.
I could try to write some tests for `AsyncS3Storage `.

**Comment by karpetrosyan** [comment]
> I could try to write some tests for `AsyncS3Storage `.

They should be identical to other storage tests
