### ISSUE TITLE
Rewriting response headers with HTTPX event hooks

### ISSUE THREAD

**Issue by cmarqu** [karpetrosyan/hishel#173]
I want to use Hishel (looks very nice, thanks!) with an API that *always* returns "cache-control: no-cache,no-store" - I want to ignore this header, always cache, and do my cache invalidation manually.

What works fine is using `extensions={"force_cache": True}`, but since I am using HTTPX only indirectly via a client generated by https://github.com/openapi-generators/openapi-python-client, I cannot easily inject that setting for every request.

Luckily, I can use HTTPX event hooks (https://www.python-httpx.org/advanced/#event-hooks) to rewrite the response header - I thought. It seems that Hishel does not get the rewritten headers but the original ones.

My code is:

```python3
    async def log_response(response):
        request = response.request
        print(f"Response: {request.method} {request.url} - Status {response.status_code} - Cache-Control: {response.headers.get('cache-control')}")

    async def patch_response(response):
        response.headers["cache-control"] = "max-age=31536000"  # 1 year (the maximum recommended by RFC2616)
        del response.headers["pragma"]

    cache_transport = hishel.AsyncCacheTransport(transport=httpx.AsyncHTTPTransport(
        verify=os.getenv("REQUESTS_CA_BUNDLE"),
    ))
    client = AuthenticatedClient(
        base_url=base_url,
        token=token,
        httpx_args={
            "transport": cache_transport,
            "event_hooks": {  # https://www.python-httpx.org/advanced/#event-hooks
                "response": [patch_response, log_response],
            },
        },
    )
```

`AuthenticatedClient` is a client like this one: https://github.com/openapi-generators/openapi-python-client/blob/9600088a213f4d2000b19e327080c1f5bf4b964c/end_to_end_tests/golden-record/my_test_api_client/client.py#L136

The `log_response` function prints out my patched `cache-control` header value,
but I see that Hishel takes the following path in the `is_cachable` function: https://github.com/karpetrosyan/hishel/blob/494fe020821a3a6cc789123e835e6f1129a55147/hishel/_controller.py#L171-L172.

Is this a bug?
What else could I try? Thanks!

**Comment by karpetrosyan** [comment]
Hi!

The problem is that event_hooks are more closer to the client, than transports.

Here is the example of HTTPX request path:

CLIENT -> HANDLE_AUTH -> HANDLE_REDIRECTS -> ... -> HANDLE_HOOKS -> TRANSPORTS -> HTTPCORE CONNECTION POOL

If you change the **REQUEST** header in a event look, your transport should see that header.
**BUT** if you change a response header, your transport can't see it.

Hishel provides transports, so it can not see the patched header because event_hooks are not processed at that moment.

If you want to remove modify cache-control header, you can do something like this:

```python
 import os

import httpx
import hishel


async def log_response(response):
    request = response.request
    print(
        f"Response: {request.method} {request.url} - Status {response.status_code} - Cache-Control: {response.headers.get('cache-control')}"
    )


class PatchResponseTransport(httpx.AsyncBaseTransport):
    def __init__(self, transport: httpx.AsyncBaseTransport):
        self._next_transport = transport

    async def async_handle_request(self, request):
        response = await self._next_transport.async_handle_request(request)
        response.headers[
            "cache-control"
        ] = "max-age=31536000"  # 1 year (the maximum recommended by RFC2616)
        del response.headers["pragma"]
        return response


patch_transport = PatchResponseTransport(
    transport=httpx.AsyncHTTPTransport(verify=os.getenv("REQUESTS_CA_BUNDLE"))
)
cache_transport = hishel.AsyncCacheTransport(transport=patch_transport)
client = AuthenticatedClient(
    base_url=base_url,
    token=token,
    httpx_args={
        "transport": cache_transport,
        "event_hooks": {  # https://www.python-httpx.org/advanced/#event-hooks
            "response": [log_response],
        },
    },
)
```

**Comment by cmarqu** [comment]
As a note to future readers, since hishel 0.0.25, this can be done simpler by using `force_cache=True` on the controller: https://hishel.com/advanced/controllers/#force-caching
