### ISSUE TITLE
Test dependencies import as part of ci/cd?

### ISSUE THREAD

**Issue by umnovI** [karpetrosyan/hishel#188]
I was wondering if there is a way for us to test dependencies as part of github actions?
So something like this could be avoided #185

**Comment by umnovI** [comment]
Maybe add a new job that runs just simple client tests with only required dependencies installed?

**Comment by karpetrosyan** [comment]
Seems like other libs are just testing such cases manually.

**Comment by umnovI** [comment]
Interesting 🤔

**Comment by umnovI** [comment]
I'll close it for now then.
