### ISSUE TITLE
Default TTL?

### ISSUE THREAD

**Issue by Ravencentric** [karpetrosyan/hishel#202]
The [docs](https://hishel.com/advanced/storages/#filesystem-storage) don't explicity say what's the default TTL and looking at the code all I can find is `None`. Does None imply here that it's kept as long as it's not stale?

**Comment by karpetrosyan** [comment]
Hi!

`ttl` is simply a limitation for the response to live in our storages; if it is None, which is the normal behavior, it can remain in our storages until the controller decides to remove it.

You are right, we definitely need to mention that in the docs.

**Comment by Ravencentric** [comment]
Understood, thank you!

**Comment by Simon-Will** [comment]
Hey, I created a trivial PR for this in #250.

**Comment by Simon-Will** [comment]
I think this can be closed. I forgot to use the "Closes X" in the PR.
