### ISSUE TITLE
AttributeError: module 'httpcore' has no attribute

### ISSUE THREAD

**Issue by NeedNot** [karpetrosyan/hishel#209]
If I use httpcore 1.0.5 I get the error

`
AttributeError: module 'httpcore' has no attribute 'CloseError'
`
if I go to 0.13.7 I get the error
`
AttributeError: module 'httpcore' has no attribute 'URL'
`
which version of httpcore do I need?

**Comment by karpetrosyan** [comment]
Hi!

I can't reproduce the issue with the httpcore 1.0.5
Can you supply some simple code that reproduces the problem? Pip freeze, Python version, and full traceback would also be helpful.

**Comment by NeedNot** [comment]
oh ur so right, How did I not see that it was being caused by something else completely unrelated with hishel

**Comment by NeedNot** [comment]
ended up fixing it by uninstalling hishel, httpx, httpcore and then installing hishel and it installed the correct versions of httpx and httpcore and now it works
