### ISSUE TITLE
Invalidate a stored request manually/on-demand

### ISSUE THREAD

**Issue by HassanRady** [karpetrosyan/hishel#227]
I have a cached endpoint and non cached dynamically endpoint and there is a dependency between them, so if there is a misalignment between them I want to hit the database for the cached endpoint. Is there a way to invoke the stored data from using the async transport in the httpx client?

**Comment by karpetrosyan** [comment]
Hi!

Is [only-if-cached](http://hishel.com/advanced/http_headers/#only-if-cached) something that can help you?

**Comment by HassanRady** [comment]
Hi

Can I use the revalidate header to store that request at that point?

**Comment by karpetrosyan** [comment]
I am not sure I fully understand what you want to do here. Can you clarify a bit?

**Comment by HassanRady** [comment]
I have a cached response that I want to invalidate/reinvalidate it on-demand. In that case, I could use the revalidate flag in the controller with the transport and inject it into the session.
