### ISSUE TITLE
Add `is_cached` functionality

### ISSUE THREAD

**Issue by realjanpaulus** [karpetrosyan/hishel#261]
Is there a possibility to check if a request is cached already?

### Where do I use it?

In a custom cache rate limiter class (which just inherits from `hishel.AsyncCacheClient`), I added this workaround:

```python
from httpx import Request

def is_cached(self, request: Request) -> bool:
    """Check if a request is cached."""

    httpcore_request = httpcore.Request(
        method=request.method,
        url=httpcore.URL(
            scheme=request.url.raw_scheme,
            host=request.url.raw_host,
            port=request.url.port,
            target=request.url.raw_path,
        ),
        headers=request.headers.raw,
        content=request.stream,
        extensions=request.extensions,
    )

    try:
        base_path = self._storage._base_path
        key = self._controller._key_generator(httpcore_request, b"")

        response_path = base_path / key

        if response_path.exists():
            return True
        else:
            return False
    except Exception as e:
        return False
```

But obviously this is not ideal as I have to add my own function and I access private attributes.

**Comment by karpetrosyan** [comment]
Hi!

I think you can use `only-if-cached` like so

```python
import hishel

client = hishel.CacheClient()

response = client.get("https://hishel.com", headers={"Cache-Control": "only-if-cached"})

is_stored = response.status_code != 504
print(is_stored)
```

It will return a 504 status code and will not send a request if it's not found in the cache. 
However, it also loads the response data into memory, so be careful.

This solution will not check if the request was cached or not; instead, it will determine if there is a cached response that can be used for this request. If a cached response exists but is, for example, stale, it will not count it as cached.

**Comment by realjanpaulus** [comment]
Thanks for the quick answer! 
A functionality to check if a request is in the local `.cache` folder would still be good to have but this workaround by testing the status code also works.
