### ISSUE TITLE
Detailed logs for understanding why a particular response was or was not cached.

### ISSUE THREAD

**Issue by karpetrosyan** [karpetrosyan/hishel#274]
Things that we need to log

- the process of constructing the response from the cache `Controller.construct_response_from_cache`
- the process of sending/receiving the revalidation request

We could also consider logging for storage and serializers, but first and foremost, we need logging for the controller and the transport that orchestrates the process, to understand why a particular request was or was not cached. This is crucial for newcomers because it’s not always obvious why a resource wasn’t cached.

**Comment by cmarqu** [comment]
Related: https://github.com/karpetrosyan/hishel/issues/190#issuecomment-2213302816
