### ISSUE TITLE
Enhancement: Force caching despite "no-cache" response directive

### ISSUE THREAD

**Issue by cubinet-code** [karpetrosyan/hishel#85]
Hi @karosis88 ,

Thank you for this package. I understand you are closely implementing RFC9111. 

However it would be useful to still cache certain responses despite the server sending no-cache or similar headers:
```
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "expires": "0",
  "pragma": "no-cache",
```

Is there currently a way to force caching?

best regards,

Oliver.

**Comment by karosis88** [comment]
Hi Oliver!

I am very happy to see that you like this package!

That's a really interesting question. I think you can do it by overriding some methods in the Controller class, like this:

```python
import httpx
from httpcore import Request, Response

import hishel


class ForceCachingController(hishel.Controller):
    def is_cachable(self, request: Request, response: Response) -> bool:
        return True

    def construct_response_from_cache(
        self, request: Request, response: Response, original_request: Request
    ) -> Response | Request | None:
        return response


cache_transport = hishel.CacheTransport(
    transport=httpx.HTTPTransport(), controller=ForceCachingController()
)
client = httpx.Client(transport=cache_transport)

```

But you should know that this can be very dangerous because the server relies on the fact that the response won't be cached.

**Comment by karosis88** [comment]
Also, the no-cache directive on its own cannot tell if the response should be cached or not; it just says that the response should be re-validated before reusing, but if the no-store directive is present, that means the response can't be cached.

**Comment by cubinet-code** [comment]
Thank you for the suggestion. 

The reason for my question is that we work with APIs that have a fee per request associated. For some requests it would still make sense to cache them for a certain period of time to not incur that fee.

Would you be open for me submitting a PR implementing this in the controller class with an attribute to force caching (possibly with an optional expiry time)?

best regards,

Oliver.

**Comment by karosis88** [comment]
I think it's better to inherit from the base class, implement such non-ordinary caching strategies, and keep Hishel's API minimalistic and clean.

I think the controller that I have shown is sufficient for your case. 
You can also set the response timeout, as shown in the example.

**Comment by cubinet-code** [comment]
Just for completeness and if somebody else is looking for this:

I ended up modifying the behaviour of `max-stale` slightly.
This allows `max-stale` also for responses that would otherwise not be cached. 

Example: `self.client.request( "GET", url, headers=[("Cache-Control", "max-stale=60")])`

This will force caching normally non-cacheable requests for 60 seconds

```
from hishel._controller import (
    get_age,
    parse_cache_control,
    extract_header_values_decoded,
)

class ForceCachingController(hishel.Controller):
    """A controller that force caches responses with a request max-stale directive"""

    def is_cachable(self, request: Request, response: Response) -> bool:
        request_cache_control = parse_cache_control(extract_header_values_decoded(request.headers, b"cache-control"))
        if request_cache_control.max_stale is not None:
            return True
        super().is_cachable(request, response)

    def construct_response_from_cache(self, request: Request, response: Response, original_request: Request) -> Response | Request | None:
        request_cache_control = parse_cache_control(extract_header_values_decoded(request.headers, b"Cache-Control"))
        if get_age(response, self._clock) < request_cache_control.max_stale:
            return response
        super().construct_response_from_cache(request, response, original_request)

...
controller = ForceCachingController()
...
```

**Comment by karpetrosyan** [comment]
It's amazing. Thank you for this issue!
